- type: jobRequirementOverride
  id: MSLaunchReduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h
    HeadOfPersonnel:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 1h

    SalvageSpecialist:
    Quartermaster:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 1h
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 1h
    StationEngineer:
    AtmosphericTechnician:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    ChiefEngineer:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 1h
    MedicalDoctor:
    Paramedic:
    Chemist:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    ChiefMedicalOfficer:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 1h
    Scientist:
    ResearchDirector:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 2h
    Borg:
    - !type:OverallPlaytimeRequirement
      time: 1h
    StationAi:
    - !type:RoleTimeRequirement
      role: JobBorg
      time: 2h
    SecurityCadet:
    - !type:OverallPlaytimeRequirement
      time: 1h
    SecurityOfficer:
    - !type:OverallPlaytimeRequirement
      time: 1h
    Detective:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
    Warden:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 3h
    HeadOfSecurity:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 2h
    Mime:
