blank_issues_enabled: true
contact_links:
  - name: Request a Feature
    url: https://discord.com/invite/monkestation
    about: Submit feature requests on our Discord server (https://discord.com/invite/monkestation).
