- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Elkridge
  - Marathon
  - Packed
  - Plasma
  - Exo
  - Snowball
  - Sushi
  - Tram2
  # Monke maps start
  - StarlightCluster
  - Reach
  - Fland
  - Oasis
  - Serpentcrest
  # Monke maps end
